# Generated by Django 5.1.7 on 2025-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', models.CharField(max_length=100)),
                ('from_postcode', models.CharField(max_length=20)),
                ('to_country', models.CharField(max_length=100)),
                ('to_postcode', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('unit_metric', models.BooleanField(default=True)),
            ],
        ),
    ]
